# .github/actions/sonarqube/action.yml
name: SonarQube
description: Run SonarQube
author: mighty-muffin

runs:
  using: composite
  steps:
    - name: Run SonarQube
      run: |
        echo "Run SonarQube"
      shell: bash

    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Connect Tailscale VPN
      uses: tailscale/github-action@84a3f23bb4d843bcf4da6cf824ec1be473daf4de # v3.2.3
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
        tags: "tag:ci"
        version: "latest"
        use-cache: "true"

    - name: Run SAST - SonarQube
      uses: SonarSource/sonarqube-scan-action@2500896589ef8f7247069a56136f8dc177c27ccf # v5.2.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Quality gating SAST - SonarQube
      if: ${{ inputs.sonarqube_gating }}
      uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # v1.2.0
      with:
        projectKey: ${{ github.event.repository.name }}
        projectName: ${{ github.event.repository.name }}
        projectVersion: ${{ github.event.repository.default_branch }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}