---
name: CI - Schedule

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  pre-commit:
    name: Call Pre-Commit
    uses: irishlab-io/.github/.github/workflows/reusable-pre-commit.yml@main

  secret:
    needs:
      - pre-commit
    name: Call Secret Scanning
    uses: irishlab-io/.github/.github/workflows/reusable-secret.yml@main

    secrets:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  sca:
    needs:
      - pre-commit
    name: Placeholder - SCA
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Run SCA
        run: echo Software Composition Analysis
        shell: bash

  sast:
    needs:
      - pre-commit
    name: Call SAST
    uses: irishlab-io/.github/.github/workflows/reusable-sast.yml@main

    with:
      sonarqube: true
      snyk: false

    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

  unit-test:
    needs:
      - secret
      - sca
      - sast
    name: Unit & Integrations Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Run Unit & Integrations Tests
        uses: mighty-muffin/js-app/.github/actions/unit-test@main
  
  docker-build:
    needs:
      - secret
      - pre-commit
    name: Call Docker Build
    uses: irishlab-io/.github/.github/workflows/reusable-docker-build.yml@main

    permissions:
      contents: read
      packages: write
      pull-requests: write

    with:
      file: "./Dockerfile"
      platforms: |
          linux/amd64
      push: false

  container-vulnerability:
    needs:
      - docker-build
      - unit-test
    name: Placeholder - Container Vulnerability Scan
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Run Container Vulnerability Scan
        run: echo Container Vulnerability Scan
        shell: bash

  cron-gating:
    needs:
      - container-vulnerability
      - unit-test
    name: Placeholder - CRON Gating
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Run CRON Gating
        run: echo CRON Gating
        shell: bash
