---
name: CI - Main

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
    tags:
      - v*

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  pre-commit:
    name: Call Pre-Commit
    uses: irishlab-io/.github/.github/workflows/reusable-pre-commit.yml@main

  secret:
    needs:
      - pre-commit
    name: Call Secret Scanning
    uses: irishlab-io/.github/.github/workflows/reusable-secret.yml@main
    secrets:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  sca:
    needs:
      - pre-commit
    name: Placeholder - SCA
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Run SCA
        run: echo Software Composition Analysis
        shell: bash

  sast:
    needs:
      - pre-commit
    name: Call SAST
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Run SAST
        run: echo Software Analysis Security Testing
        shell: bash

  unit-test:
    needs:
      - secret
      - sca
      - sast
    name: Unit & Integrations Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Run Unit & Integrations Tests
        uses: mighty-muffin/js-app/.github/actions/unit-test@main
  
  docker-build:
    needs:
      - secret
      - pre-commit
    name: Call Docker Build
    uses: irishlab-io/.github/.github/workflows/reusable-docker-build.yml@main

    permissions:
      contents: read
      packages: write
      pull-requests: write

    with:
      file: "./Dockerfile"
      platforms: |
          linux/amd64
          linux/arm64

  container-vulnerability:
    needs:
      - docker-build
      - unit-test
    name: Placeholder - Container Vulnerability Scan
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Run Container Vulnerability Scan
        run: echo Container Vulnerability Scan
        shell: bash

  container-push:
    needs:
      - container-vulnerability
      - unit-test
    name: Placeholder - Container Push
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Run Container Push
        run: echo Container Push
        shell: bash
