---
name: CI - PR

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  pre-commit:
    name: Call Pre-Commit
    uses: irishlab-io/.github/.github/workflows/reusable-pre-commit.yml@main

  secret:
    needs:
      - pre-commit
    name: Call Secret Scanning
    uses: irishlab-io/.github/.github/workflows/reusable-secret.yml@main
    secrets:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  sca:
    needs:
      - pre-commit
    name: Placeholder - SCA
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    permissions:
      actions: read
      contents: write

    steps:
      - name: Run SCA
        run: echo Software Composition Analysis
        shell: bash
        
      - name: Run Syft
        uses: anchore/sbom-action@v0.20.4

      - name: Run FOSSA 
        uses: fossas/fossa-action@v1.7.0
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}

  sast:
    needs:
      - pre-commit
    name: Call SAST
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Run SAST
        run: echo Software Analysis Security Testing
        shell: bash

  sast-codeql:
    needs:
      - pre-commit
    name: Call CodeQL
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        language: [ javascript, typescript]

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@d6bbdef45e766d081b84a2def353b0055f728d3e # v3.29.3
        with:
          languages: java
          dependency-caching: true

      - name: Autobuild
        uses: github/codeql-action/autobuild@d6bbdef45e766d081b84a2def353b0055f728d3e # v3.29.3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@d6bbdef45e766d081b84a2def353b0055f728d3e # v3.29.3

      # - name: Upload CodeQL Results
      #   uses: github/codeql-action/upload-sarif@d6bbdef45e766d081b84a2def353b0055f728d3e # v3.29.3
      #   with:
      #     category: codeql
      #     sarif_file: codeql-results.sarif
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sast-snyk:
    needs:
      - pre-commit
    name: Call Snyk
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22

      - name: NodeJS Freeze
        run: |
          echo "NODE=$(node --version | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
        shell: bash

      - name: Enable Node.js cache
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: node | ${{ env.NODE }} | ${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: NPM Install CI
        run: |
          npm install ci
        shell: bash

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@b98d498629f1c368650224d6d212bf7dfa89e4bf # 0.4.0
        continue-on-error: true

        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

        with:
          args: --severity-threshold=high

      # - name: Upload SNYK Results
      #   uses: github/codeql-action/upload-sarif@d6bbdef45e766d081b84a2def353b0055f728d3e # v3.29.3
      #   with:
      #     category: snyk
      #     sarif_file: snyk-code.sarif
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sast-sonarqube:
    needs:
      - pre-commit
    name: Call Snyk
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Connect Tailscale VPN
        uses: tailscale/github-action@84a3f23bb4d843bcf4da6cf824ec1be473daf4de # v3.2.3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: "tag:ci"
          version: "latest"
          use-cache: "true"

      - name: Run SAST - SonarQube
        uses: SonarSource/sonarqube-scan-action@2500896589ef8f7247069a56136f8dc177c27ccf # v5.2.0
        with:
          args: |
            -Dsonar.projectKey=${{ github.event.repository.name }}
            -Dsonar.projectName=${{ github.event.repository.name }}
            -Dsonar.projectVersion=${{ github.event.repository.default_branch }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Quality gating SAST - SonarQube
        uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # v1.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  unit-test:
    needs:
      - secret
      - sca
      - sast
      - sast-codeql
      - sast-snyk
      - sast-sonarqube
    name: Unit & Integrations Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Run Unit & Integrations Tests
        uses: mighty-muffin/js-app/.github/actions/unit-test@main
  
  docker-build:
    needs:
      - secret
      - pre-commit
    name: Call Docker Build
    uses: irishlab-io/.github/.github/workflows/reusable-docker-build.yml@main

    permissions:
      contents: read
      packages: write
      pull-requests: write

    with:
      file: "./Dockerfile"
      platforms: |
          linux/amd64

  container-vulnerability:
    needs:
      - docker-build
      - unit-test
    name: Placeholder - Container Vulnerability Scan
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Run Container Vulnerability Scan
        run: echo Container Vulnerability Scan
        shell: bash

  pr-gating:
    needs:
      - container-vulnerability
      - unit-test
    name: Placeholder - PR Gating
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Run PR Gating
        run: echo PR Gating
        shell: bash
